//vLoaders
export const LOAD_SECTION = 'LOAD_SECTION'

// Open/Close categories
export const OPEN_SECTION = 'OPEN_SECTION'
export const CLOSE_SECTION = 'CLOSE_SECTION'
export const OPEN_SUBSECTION = 'OPEN_SUBSECTION'
export const CLOSE_SUBSECTION = 'CLOSE_SUBSECTION'
export const OPEN_BLOCKSECTION = 'OPEN_BLOCKSECTION'
export const CLOSE_BLOCKSECTION = 'CLOSE_BLOCKSECTION'
export const OPEN_BLOCK = 'OPEN_BLOCK'
export const CLOSE_BLOCK = 'CLOSE_BLOCK'

// Settings for the visual editor
// TODO: Add the remaining settings
export const SHOW_BLOCK = 'SHOW_BLOCK'
export const HIDE_BLOCK = 'HIDE_BLOCK'
export const CUSTOM_TEXT_COLOR = 'CUSTOM_TEXT_COLOR'
export const DEFAULT_TEXT_COLOR = 'DEFAULT_TEXT_COLOR'
export const CUSTOM_BORDER_COLOR = 'CUSTOM_BORDER_COLOR'
export const DEFAULT_BORDER_COLOR = 'DEFAULT_BORDER_COLOR'
export const CUSTOM_BACKGROUND_COLOR = 'CUSTOM_BACKGROUND_COLOR'
export const DEFAULT_BACKGROUND_COLOR = 'DEFAULT_BACKGROUND_COLOR'
export const COPY_BLOCK = 'COPY_BLOCK'
export const PASTE_BLOCK = 'PASTE_BLOCK'
export const RESET_BLOCK = 'RESET_BLOCK'

//vFetching from /headers/<header_file.json>
export const DATA_REQUESTED = 'DATA_REQUESTED'
export const DATA_RETRIEVED = 'DATA_RETRIEVED'
export const DATA_FAILED = 'DATA_FAILED'
export const SECTIONS_REQUESTED = 'SECTIONS_REQUESTED'
export const SECTIONS_RETRIEVED = 'SECTIONS_RETRIEVED'
export const SECTIONS_FAILED = 'SECTIONS_FAILED'
export const SUBSECTIONS_REQUESTED = 'SUBSECTIONS_REQUESTED'
export const SUBSECTIONS_RETRIEVED = 'SUBSECTIONS_RETRIEVED'
export const SUBSECTIONS_FAILED = 'SUBSECTIONS_FAILED'
export const BLOCKSECTIONS_REQUESTED = 'BLOCKSECTIONS_REQUESTED'
export const BLOCKSECTIONS_RETRIEVED = 'BLOCKSECTIONS_RETRIEVED'
export const BLOCKSECTIONS_FAILED = 'BLOCKSECTIONS_FAILED'
export const BLOCKS_REQUESTED = 'BLOCKS_REQUESTED'
export const BLOCKS_RETRIEVED = 'BLOCKS_RETRIEVED'
export const BLOCKS_FAILED = 'BLOCKS_FAILED'